# Generated by Django 5.1.5 on 2025-01-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rss_url', models.URLField(unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
